version: 2.1

aliases:
  - &working_directory ~/project
  - &node_docker_image
    - image: circleci/node:10.15-browsers
      environment:
        TERM: xterm
  - &restore_npm_cache
    restore_cache:
      keys:
        - v2-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - v2-npm-{{ .Branch }}
        - v2-npm-
  - &save_npm_cache
    save_cache:
      key: v2-npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  - &npm_install
    run:
      name: npm install
      command: npm install
  - &npm_build
    run:
      name: npm run build
      command: |
        export REACT_APP_BUILD_ID="${CIRCLE_SHA1:0:7}"
        npm run build

jobs:
  unit_test_and_build:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - *restore_npm_cache
      - *npm_install
      - *save_npm_cache
      - run: npm run check-fences
      - run: npm run test:ci
      - *npm_build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - build
      - store_test_results:
          path: ./reports
  build_release:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - *restore_npm_cache
      - *npm_install
      - *save_npm_cache
      - *npm_build
      - run:
          name: rename build dir to build-release
          command: mv build build-release
      - persist_to_workspace:
          root: *working_directory
          paths:
            - build-release
  visual_regression_testing:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - *restore_npm_cache
      - *npm_install
      - *save_npm_cache
      - run: npm run snapshot

workflows:
  build_and_deploy:
    jobs:
      - unit_test_and_build:
          context: because-npm-staging
      - visual_regression_testing:
          context: because-npm-staging
          filters:
            branches:
              ignore:
                - master
